### PR TITLE
Custom styles from numen

### PR DESCRIPTION
**Pull request by eldang**
This incorporates the 4 styles that numen sent me about 15 minutes ago, so presumably the latest versions.  All that I have done is to follow the instructions at https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Customizing.md so I am wary of two potential pitfalls:

1. I may be repeating whatever it was that broke @zacherybohon's earlier attempt at updating the styles.
2. We may also need to bring in other customisations currently in force at https://weirder.earth/

@zacherybohon please either merge this PR or let me know what else I should do to address the above.

### CODE REVIEW

**Comment by eldang** [comment]
I'm trying to address the circleci issues.

**Comment by eldang** [comment]
I anticipate the latest commit fixing 3 of 4 circleci failures, but I don't know how to address the i18n one.

**Comment by zacherybohon** [comment]
An additional concern: this PR is targeting master which is not where we are at

**Comment by eldang** [comment]
I'm confused - where are we at?

**Comment by zacherybohon** [comment]
Our Master is at 2.9.2. This PR is way ahead. I am constructing a new PR on s new branch. I think we will end up closing this PR without merging but for now, I’d like to leave it as is for a reference.

**Comment by eldang** [comment]
Makes sense.  It may be helpful to cherrypick 3321093 & bb95cca or it may be easier to just replicate their fairly modest changes.

**Pull request closed without merging**
